#include <array>
#include <cstdint>
#include <iostream>
#include <vector>
#include <queue>
using namespace std; constexpr int L=6; enum K:uint8_t{E=0,S=1,P=2,C=3}; struct Cell{K k=E;int8_t origin=-2;};using Grid=array<array<Cell,4>,L+1>;
int lq(int q){return(q+3)&3;}int rq(int q){return(q+1)&3;}bool occ(const Cell&c){return c.k!=E;}
uint32_t supportmask(const Grid&g,int H){uint32_t sup=0;for(int q=0;q<4;q++)if(occ(g[0][q]))sup|=1u<<q;bool ch=true;while(ch){ch=false;for(int r=1;r<H;r++)for(int q=0;q<4;q++)if(occ(g[r][q])&&(sup&(1u<<(4*(r-1)+q)))&&!(sup&(1u<<(4*r+q)))){sup|=1u<<(4*r+q);ch=true;}for(int r=0;r<H;r++)for(int q=0;q<4;q++)if(occ(g[r][q])&&g[r][q].k!=P&&!(sup&(1u<<(4*r+q))))for(int n:{lq(q),rq(q)})if(occ(g[r][n])&&g[r][n].k!=P&&(sup&(1u<<(4*r+n)))){sup|=1u<<(4*r+q);ch=true;break;}for(int r=0;r+1<H;r++)for(int q=0;q<4;q++)if(g[r][q].k==C&&g[r+1][q].k==C&&(sup&(1u<<(4*(r+1)+q)))&&!(sup&(1u<<(4*r+q)))){sup|=1u<<(4*r+q);ch=true;}}return sup;}
void del(Grid&g,int H,vector<pair<int,int>>seeds){bool vis[L+1][4]{};queue<pair<int,int>>qq;for(auto x:seeds){auto[r,q]=x;if(r>=0&&r<H&&occ(g[r][q])){vis[r][q]=1;qq.push(x);}}while(!qq.empty()){auto[r,q]=qq.front();qq.pop();if(g[r][q].k!=C)continue;for(int n:{lq(q),rq(q)})if(!vis[r][n]&&g[r][n].k==C){vis[r][n]=1;qq.push({r,n});}for(int nr:{r-1,r+1})if(nr>=0&&nr<H&&!vis[nr][q]&&g[nr][q].k==C){vis[nr][q]=1;qq.push({nr,q});}}for(int r=0;r<H;r++)for(int q=0;q<4;q++)if(vis[r][q])g[r][q]=Cell{};}
vector<int>hcomp(const Grid&g,int r,int q,uint32_t uns){vector<int>o;if(!(uns&(1u<<(4*r+q))))return o;if(g[r][q].k==P){o.push_back(q);return o;}bool seen[4]{};queue<int>qq;seen[q]=1;qq.push(q);while(!qq.empty()){int a=qq.front();qq.pop();o.push_back(a);for(int n:{lq(a),rq(a)})if(n<2&&!seen[n]&&(uns&(1u<<(4*r+n)))&&g[r][n].k!=P&&g[r][n].k!=C){seen[n]=1;qq.push(n);}}return o;}
uint8_t push(Grid pre,Grid&g){for(int q=0;q<2;q++)if(occ(pre[0][q]))g[0][q]={P,-1};for(int r=0;r<L;r++)for(int q=0;q<2;q++){g[r+1][q]=pre[r][q];if(occ(g[r+1][q]))g[r+1][q].origin=r;}vector<pair<int,int>>seeds;for(int q=0;q<2;q++)if(occ(g[L][q]))seeds.push_back({L,q});del(g,L+1,seeds);for(int q=0;q<2;q++)g[L][q]=Cell{};uint8_t fm=0;while(true){auto sup=supportmask(g,L);uint32_t all=0;for(int r=0;r<L;r++)for(int q=0;q<2;q++)if(occ(g[r][q]))all|=1u<<(4*r+q);auto uns=all&~sup;if(!uns)break;vector<pair<int,int>>uc;for(int r=0;r<L;r++)for(int q=0;q<2;q++)if((uns&(1u<<(4*r+q)))&&g[r][q].k==C)uc.push_back({r,q});if(!uc.empty()){del(g,L,uc);continue;}bool moved=false;uint32_t vis=0;for(int r=0;r<L;r++)for(int q=0;q<2;q++){uint32_t b=1u<<(4*r+q);if(!(uns&b)||(vis&b)||!occ(g[r][q]))continue;auto comp=hcomp(g,r,q,uns);for(int x:comp)vis|=1u<<(4*r+x);int d=0;while(true){int nd=d+1;bool ok=1;for(int x:comp){int tr=r-nd;if(tr<0||occ(g[tr][x])){ok=0;break;}}if(!ok)break;d=nd;}if(d){array<Cell,2>v{};for(int x:comp){v[x]=g[r][x];g[r][x]=Cell{};}for(int x:comp){g[r-d][x]=v[x];fm|=1<<x;}moved=true;}}if(!moved)break;}return fm;}
bool stable(const Grid&g){uint32_t all=0;for(int r=0;r<L;r++)for(int q=0;q<2;q++)if(occ(g[r][q]))all|=1u<<(4*r+q);return all&&supportmask(g,L)==all;}
bool hasc(const Grid&g){for(int r=0;r<L;r++)for(int q=0;q<2;q++)if(g[r][q].k==C)return true;return false;}bool topc(const Grid&g){for(int r=L-1;r>=0;r--){bool a=0,c=0;for(int q=0;q<2;q++){a|=occ(g[r][q]);c|=g[r][q].k==C;}if(a)return c;}return false;}string gs(const Grid&g){string z;for(int r=0;r<L;r++){if(r)z+=':';for(int q=0;q<2;q++)z+="-SPc"[g[r][q].k];}return z;}
int main(){uint64_t tot=1ull<<(4*L),stable_all=0,no_top_c=0,active=0;
 for(uint64_t x=0;x<tot;x++){Grid p{},o{};uint64_t y=x;for(int r=0;r<L;r++)for(int q=0;q<2;q++){p[r][q].k=K(y&3);y>>=2;}
  if(!stable(p))continue;stable_all++;if(p[L-1][0].k==C||p[L-1][1].k==C)continue;no_top_c++;
  auto fm=push(p,o);if(fm){active++;cout<<"NO_TOP_CRYSTAL_ACTIVE_COUNTER pre="<<gs(p)<<" out="<<gs(o)<<" fm="<<(int)fm<<"\n";return 0;}
 }
 cout<<"NO_NO_TOP_CRYSTAL_ACTIVE_COUNTER L="<<L<<" stable="<<stable_all<<" no_top_c="<<no_top_c<<" active="<<active<<"\n";}
