from __future__ import annotations

import argparse
import contextlib
import io
import ast
import json
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import symbolic_frontier_automaton as sfa

with contextlib.redirect_stdout(io.StringIO()):
    from claw_tracer import claw_process as _claw_process
    from data_operations import simplify_shape as _simplify_shape
    from shape import Shape as _Shape
    from shape_classifier import analyze_shape as _analyze_shape


def _legacy_type(code: str) -> tuple[str, str]:
    with contextlib.redirect_stdout(io.StringIO()):
        result, reason = _analyze_shape(code, _Shape.from_string(code))
    return str(result), str(reason)


def _skip_type(code: str) -> tuple[str, str]:
    with contextlib.redirect_stdout(io.StringIO()):
        return sfa.cached_skip_shape_analysis(repr(_Shape.from_string(code)))


def _claw_predecessor(code: str) -> str:
    with contextlib.redirect_stdout(io.StringIO()):
        raw = _claw_process(repr(_Shape.from_string(code)))
        return sfa.normalize_code(_simplify_shape(raw) if raw else "")


def _top_signature(code: str) -> str:
    normalized = sfa.normalize_code(code)
    parts = normalized.split(":") if normalized else []
    if not parts:
        return "empty"
    top = parts[-1]
    penult = parts[-2] if len(parts) >= 2 else "none"
    return f"{penult}>{top}|rem={sfa.bitmask_layer_removal_context(normalized)[:3]}"


def _axis_label(code: str, layers: int) -> str:
    swap_reason = sfa.bitmask_swap_impossibility(code)
    if swap_reason is None:
        return "half_swappable"
    if sfa.bitmask_stackability_witnesses(code):
        return f"stackable_after_{swap_reason}"
    subtype = sfa.pp_subtype_candidate(code, layers).subtype
    return f"pp:{subtype}"


def _zero_stack_depth(predecessor: str) -> int:
    current = sfa.normalize_code(predecessor)
    depth = 0
    seen: set[str] = set()
    while current and current not in seen and sfa.top_single_c_zero_stack_candidate(current):
        seen.add(current)
        parts = current.split(":")
        current = sfa.normalize_code(":".join(parts[1:]))
        depth += 1
    return depth


def _layer_delta_signature(base: str, predecessor: str, max_layers: int) -> tuple[tuple[int, str, str], ...]:
    base_parts = sfa.normalize_code(base).split(":") if sfa.normalize_code(base) else []
    pred_parts = sfa.normalize_code(predecessor).split(":") if sfa.normalize_code(predecessor) else []
    out: list[tuple[int, str, str]] = []
    for layer in range(max_layers):
        before = base_parts[layer] if layer < len(base_parts) else "----"
        after = pred_parts[layer] if layer < len(pred_parts) else "----"
        if before != after:
            out.append((layer, before, after))
    return tuple(out)


def _write_delta_transitions_py(args: argparse.Namespace, transitions: Counter[tuple[int, str, str]]) -> None:
    if args.write_delta_transitions_py is None:
        return
    selected = [
        transition
        for transition, count in transitions.most_common()
        if count >= args.min_delta_transition_count
    ]
    lines = [
        "# Generated by analyze_claw_preimages.py --delta-grammar-report.",
        "CLAW_DELTA_LAYER_TRANSITIONS = (",
    ]
    for transition in selected:
        lines.append(f"    {transition!r},")
    lines.append(")")
    args.write_delta_transitions_py.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _parse_transition_key(key: str) -> tuple[int, str, str]:
    value = ast.literal_eval(key)
    if not (
        isinstance(value, tuple)
        and len(value) == 3
        and isinstance(value[0], int)
        and isinstance(value[1], str)
        and isinstance(value[2], str)
    ):
        raise ValueError(f"invalid transition key: {key!r}")
    return value


def analyze(args: argparse.Namespace) -> int:
    started = time.perf_counter()
    total = processed = push_matches = empty_pred = errors = 0
    unique_predecessors: set[str] = set()
    predecessor_fanout: Counter[str] = Counter()
    pred_type_counts: Counter[tuple[str, str]] = Counter()
    pred_skip_type_counts: Counter[tuple[str, str]] = Counter()
    pred_decomposition_counts: Counter[str] = Counter()
    pred_axis_counts: Counter[str] = Counter()
    target_layers: Counter[int] = Counter()
    predecessor_layers: Counter[int] = Counter()
    predecessor_c_counts: Counter[int] = Counter()
    predecessor_highest_c: Counter[tuple[int, int, str]] = Counter()
    target_top_signatures: Counter[str] = Counter()
    predecessor_top_signatures: Counter[str] = Counter()
    zero_stack_seed_axis_counts: Counter[str] = Counter()
    zero_stack_depth_counts: Counter[int] = Counter()
    zero_stack_seed_top_signatures: Counter[str] = Counter()
    delta_grammar_counts: Counter[tuple[tuple[int, str, str], ...]] = Counter()
    delta_layer_transition_counts: Counter[tuple[int, str, str]] = Counter()
    mismatch_samples: list[str] = []
    error_samples: list[str] = []
    fanout_samples: defaultdict[str, list[str]] = defaultdict(list)

    for code in sfa.iter_data_codes(args.data, max_layers=args.layers):
        if args.limit and total >= args.limit:
            break
        if args.max_seconds and time.perf_counter() - started > args.max_seconds:
            break
        target = sfa.normalize_code(code)
        if not target:
            continue
        total += 1
        target_layers[len(target.split(":"))] += 1
        try:
            pred = _claw_predecessor(target)
            processed += 1
        except Exception as exc:
            errors += 1
            if len(error_samples) < args.max_samples:
                error_samples.append(f"{target}\terror={type(exc).__name__}:{exc}")
            continue
        if not pred:
            empty_pred += 1
            if len(mismatch_samples) < args.max_samples:
                mismatch_samples.append(f"{target}\tempty_predecessor")
            continue
        unique_predecessors.add(pred)
        pred_parts = pred.split(":") if pred else []
        predecessor_layers[len(pred_parts)] += 1
        predecessor_c_counts[sum(layer.count("c") for layer in pred_parts)] += 1
        highest_c_layer = -1
        highest_c_count = 0
        highest_c_text = ""
        for layer_idx in range(len(pred_parts) - 1, -1, -1):
            count = pred_parts[layer_idx].count("c")
            if count:
                highest_c_layer = layer_idx
                highest_c_count = count
                highest_c_text = pred_parts[layer_idx]
                break
        predecessor_highest_c[(highest_c_layer, highest_c_count, highest_c_text)] += 1
        predecessor_fanout[pred] += 1
        if len(fanout_samples[pred]) < 3:
            fanout_samples[pred].append(target)
        target_top_signatures[_top_signature(target)] += 1
        predecessor_top_signatures[_top_signature(pred)] += 1
        replay = sfa.bitmask_push_pin(pred, max(args.layers, len(target.split(":"))))
        if replay == target:
            push_matches += 1
        elif len(mismatch_samples) < args.max_samples:
            mismatch_samples.append(f"{target}\tpred={pred}\tpush={replay}")
        if args.classify_predecessor:
            try:
                pred_type_counts[_legacy_type(pred)] += 1
            except Exception as exc:
                pred_type_counts[(type(exc).__name__, "classification_error")] += 1
            try:
                pred_skip_type_counts[_skip_type(pred)] += 1
            except Exception as exc:
                pred_skip_type_counts[(type(exc).__name__, "skip_classification_error")] += 1
        if args.decompose_predecessor:
            if sfa.reference_cpcp_swappable_witness(pred, args.layers) is not None:
                pred_decomposition_counts["reference_swappable"] += 1
            elif sfa.reference_stackability_core_verdict(pred, args.layers) is not None:
                pred_decomposition_counts["reference_stackable"] += 1
            else:
                subtype = sfa.pp_subtype_candidate(pred, args.layers).subtype
                pred_decomposition_counts[subtype] += 1
        if args.axis_decompose_predecessor:
            pred_axis_counts[_axis_label(pred, args.layers)] += 1
        if args.zero_stack_seed_report:
            subtype = sfa.pp_subtype_candidate(pred, args.layers).subtype
            if subtype == "top_single_c_zero_stack_unresolved_pp_candidate":
                seed = sfa.zero_stack_trace_seed(
                    pred,
                    args.layers,
                    allow_terminal_crystal=args.allow_terminal_crystal,
                )
                if seed is None:
                    zero_stack_seed_axis_counts["missing_seed"] += 1
                else:
                    seed_current, _seed_base = seed
                    zero_stack_seed_axis_counts[_axis_label(seed_current, args.layers)] += 1
                    zero_stack_depth_counts[_zero_stack_depth(pred)] += 1
                    zero_stack_seed_top_signatures[_top_signature(seed_current)] += 1
        if args.delta_grammar_report:
            base = sfa.normalize_code(":".join(target.split(":")[1:]))
            signature = _layer_delta_signature(base, pred, args.layers)
            delta_grammar_counts[signature] += 1
            for transition in signature:
                delta_layer_transition_counts[transition] += 1

    elapsed = time.perf_counter() - started
    summary = {
        "input": str(args.data),
        "layers": args.layers,
        "total": total,
        "processed": processed,
        "errors": errors,
        "empty_predecessor": empty_pred,
        "push_matches": push_matches,
        "push_match_rate": (100.0 * push_matches / processed if processed else 100.0),
        "unique_predecessors": len(unique_predecessors),
        "elapsed": elapsed,
        "predecessor_axis_decomposition": dict(pred_axis_counts),
        "predecessor_decomposition": dict(pred_decomposition_counts),
        "target_layer_counts": dict(target_layers),
        "predecessor_layer_counts": dict(predecessor_layers),
        "predecessor_c_counts": dict(predecessor_c_counts),
        "predecessor_highest_c": {
            f"layer={layer}|c_count={c_count}|text={text}": count
            for (layer, c_count, text), count in predecessor_highest_c.items()
        },
        "target_top_signatures": dict(target_top_signatures),
        "predecessor_top_signatures": dict(predecessor_top_signatures),
        "zero_stack_seed_axis_counts": dict(zero_stack_seed_axis_counts),
        "zero_stack_depth_counts": dict(zero_stack_depth_counts),
        "zero_stack_seed_top_signatures": dict(zero_stack_seed_top_signatures),
        "delta_grammar_counts": {repr(key): count for key, count in delta_grammar_counts.items()},
        "delta_layer_transition_counts": {repr(key): count for key, count in delta_layer_transition_counts.items()},
    }
    if args.write_json:
        args.write_json.parent.mkdir(parents=True, exist_ok=True)
        args.write_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    if args.delta_grammar_report:
        _write_delta_transitions_py(args, delta_layer_transition_counts)
    print(f"input={args.data}")
    print(f"layers={args.layers}")
    print(f"total={total}")
    print(f"processed={processed}")
    print(f"errors={errors}")
    print(f"empty_predecessor={empty_pred}")
    print(f"push_matches={push_matches}")
    print(f"push_match_rate={100.0 * push_matches / processed if processed else 100:.6f}%")
    print(f"unique_predecessors={len(unique_predecessors)}")
    print(f"elapsed={elapsed:.6f}s")
    if predecessor_fanout:
        print("top_predecessor_fanout:")
        for pred, count in predecessor_fanout.most_common(12):
            print(f"  {count}: {pred} -> {fanout_samples[pred]}")
    if pred_type_counts:
        print("predecessor_legacy_types:")
        for (kind, reason), count in pred_type_counts.most_common(20):
            print(f"  {count}: {kind}/{reason}")
    if pred_skip_type_counts:
        print("predecessor_skip_types:")
        for (kind, reason), count in pred_skip_type_counts.most_common(20):
            print(f"  {count}: {kind}/{reason}")
    if pred_decomposition_counts:
        print("predecessor_decomposition:")
        for key, count in pred_decomposition_counts.most_common(24):
            print(f"  {key}: {count}")
    if pred_axis_counts:
        print("predecessor_axis_decomposition:")
        for key, count in pred_axis_counts.most_common(24):
            print(f"  {key}: {count}")
    if zero_stack_seed_axis_counts:
        print("zero_stack_seed_axis_decomposition:")
        for key, count in zero_stack_seed_axis_counts.most_common(24):
            print(f"  {key}: {count}")
    if zero_stack_depth_counts:
        print("zero_stack_prefix_depth_counts:")
        for key, count in sorted(zero_stack_depth_counts.items()):
            print(f"  {key}: {count}")
    print("target_layer_counts:")
    for layer, count in sorted(target_layers.items()):
        print(f"  {layer}: {count}")
    print("predecessor_layer_counts:")
    for layer, count in sorted(predecessor_layers.items()):
        print(f"  {layer}: {count}")
    print("predecessor_c_counts:")
    for c_count, count in predecessor_c_counts.most_common(20):
        print(f"  {c_count}: {count}")
    print("predecessor_highest_c:")
    for (layer, c_count, text), count in predecessor_highest_c.most_common(20):
        print(f"  {count}: layer={layer} c_count={c_count} text={text}")
    print("target_top_signatures:")
    for sig, count in target_top_signatures.most_common(16):
        print(f"  {count}: {sig}")
    print("predecessor_top_signatures:")
    for sig, count in predecessor_top_signatures.most_common(16):
        print(f"  {count}: {sig}")
    if zero_stack_seed_top_signatures:
        print("zero_stack_seed_top_signatures:")
        for sig, count in zero_stack_seed_top_signatures.most_common(16):
            print(f"  {count}: {sig}")
    if delta_grammar_counts:
        print("delta_grammar_signatures:")
        for signature, count in delta_grammar_counts.most_common(args.max_delta_signatures):
            print(f"  {count}:")
            for layer, before, after in signature:
                print(f"    L{layer}: {before} -> {after}")
    if delta_layer_transition_counts:
        print("delta_layer_transitions:")
        for (layer, before, after), count in delta_layer_transition_counts.most_common(args.max_delta_transitions):
            print(f"  {count}: L{layer}: {before} -> {after}")
    if mismatch_samples:
        print("mismatch_samples:")
        for sample in mismatch_samples:
            print(sample)
    if error_samples:
        print("error_samples:")
        for sample in error_samples:
            print(sample)
    if args.write_json:
        print(f"wrote_json={args.write_json}")
    if args.write_delta_transitions_py:
        print(f"wrote_delta_transitions_py={args.write_delta_transitions_py}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Analyze claw dataset as claw_process preimages.")
    parser.add_argument("--data", type=Path, default=PROJECT_ROOT / "data" / "all40171clawsnohybrid.txt")
    parser.add_argument("--layers", type=int, default=5)
    parser.add_argument("--limit", type=int, default=1000)
    parser.add_argument("--max-seconds", type=float, default=120.0)
    parser.add_argument("--classify-predecessor", action="store_true")
    parser.add_argument("--decompose-predecessor", action="store_true")
    parser.add_argument("--axis-decompose-predecessor", action="store_true")
    parser.add_argument("--zero-stack-seed-report", action="store_true")
    parser.add_argument("--allow-terminal-crystal", action="store_true")
    parser.add_argument("--delta-grammar-report", action="store_true")
    parser.add_argument("--max-delta-signatures", type=int, default=24)
    parser.add_argument("--max-delta-transitions", type=int, default=40)
    parser.add_argument("--write-delta-transitions-py", type=Path, default=None)
    parser.add_argument("--min-delta-transition-count", type=int, default=1)
    parser.add_argument("--write-json", type=Path, default=None)
    parser.add_argument("--max-samples", type=int, default=8)
    return analyze(parser.parse_args())


if __name__ == "__main__":
    raise SystemExit(main())
